kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: image-pusher
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-demo-sa
    namespace: quarkus-observability
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipelines-scc-clusterrole
