kind: OpenTelemetryCollector
apiVersion: opentelemetry.io/v1beta1
metadata:
  name: otel
  namespace: quarkus-observability
spec:
  config:
    exporters:
      otlp/jaeger:
        endpoint: jaeger-all-in-one-inmemory-collector:4317
        tls:
          insecure: true
      debug: {}
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
    service:
      pipelines:
        traces:
          exporters:
            - otlp/jaeger
          receivers:
            - otlp
          processors:
            #- batch